# fly.toml app configuration file generated for fly-io-tutorial on 2023-05-06T21:01:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-io-tutorial"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
