app = "fly-io-tutorial"
primary_region = "nrt"

[processes]
  web = "bin/rails server"
  cron = "supercronic /rails/crontab"

[http_service]
  processes = ["web"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
